#pragma once

#define AddLuaGlobalInt(n, name) lua_pushinteger(L, n); lua_setglobal(L, name)
#define AddLuaGlobalUData(d, name) lua_pushlightuserdata(L, d); lua_setglobal(L, name)

static int LuaFN_GLFWGetCursorPos(lua_State* L)
{
	GLFWwindow* glWindow = (GLFWwindow*)lua_touserdata(L, lua_upvalueindex(1));
	double x, y;
	glfwGetCursorPos(glWindow, &x, &y);

	lua_pushnumber(L, x);
	lua_pushnumber(L, y);
	return 2;
}

static int LuaFN_GLFWSetInputMode(lua_State* L)
{
	GLFWwindow* glWindow = (GLFWwindow*)lua_touserdata(L, lua_upvalueindex(1));

	glfwSetInputMode(glWindow, lua_tointeger(L, 1), lua_tointeger(L, 2));
	return 0;
}

void Lua_AddGLFWLib(lua_State* L, GLFWwindow* glWindow)
{
	AddLuaGlobalInt(GLFW_PRESS, "GLFW_PRESS");
	AddLuaGlobalInt(GLFW_RELEASE, "GLFW_RELEASE");
	AddLuaGlobalInt(GLFW_REPEAT, "GLFW_REPEAT");

	AddLuaGlobalInt(GLFW_NO_API, "GLFW_NO_API");
	AddLuaGlobalInt(GLFW_OPENGL_API, "GLFW_OPENGL_API");
	AddLuaGlobalInt(GLFW_OPENGL_ES_API, "GLFW_OPENGL_ES_API");
	AddLuaGlobalInt(GLFW_NO_ROBUSTNESS, "GLFW_NO_ROBUSTNESS");
	AddLuaGlobalInt(GLFW_NO_RESET_NOTIFICATION, "GLFW_NO_RESET_NOTIFICATION");
	AddLuaGlobalInt(GLFW_LOSE_CONTEXT_ON_RESET, "GLFW_LOSE_CONTEXT_ON_RESET");
	AddLuaGlobalInt(GLFW_OPENGL_ANY_PROFILE, "GLFW_OPENGL_ANY_PROFILE");
	AddLuaGlobalInt(GLFW_OPENGL_CORE_PROFILE, "GLFW_OPENGL_CORE_PROFILE");
	AddLuaGlobalInt(GLFW_OPENGL_COMPAT_PROFILE, "GLFW_OPENGL_COMPAT_PROFILE");
	AddLuaGlobalInt(GLFW_CURSOR, "GLFW_CURSOR");
	AddLuaGlobalInt(GLFW_STICKY_KEYS, "GLFW_STICKY_KEYS");
	AddLuaGlobalInt(GLFW_STICKY_MOUSE_BUTTONS, "GLFW_STICKY_MOUSE_BUTTONS");
	AddLuaGlobalInt(GLFW_LOCK_KEY_MODS, "GLFW_LOCK_KEY_MODS");
	AddLuaGlobalInt(GLFW_RAW_MOUSE_MOTION, "GLFW_RAW_MOUSE_MOTION");
	AddLuaGlobalInt(GLFW_CURSOR_NORMAL, "GLFW_CURSOR_NORMAL");
	AddLuaGlobalInt(GLFW_CURSOR_HIDDEN, "GLFW_CURSOR_HIDDEN");
	AddLuaGlobalInt(GLFW_CURSOR_DISABLED, "GLFW_CURSOR_DISABLED");
	AddLuaGlobalInt(GLFW_CURSOR_CAPTURED, "GLFW_CURSOR_CAPTURED");
	AddLuaGlobalInt(GLFW_ANY_RELEASE_BEHAVIOR, "GLFW_ANY_RELEASE_BEHAVIOR");
	AddLuaGlobalInt(GLFW_RELEASE_BEHAVIOR_FLUSH, "GLFW_RELEASE_BEHAVIOR_FLUSH");
	AddLuaGlobalInt(GLFW_RELEASE_BEHAVIOR_NONE, "GLFW_RELEASE_BEHAVIOR_NONE");
	AddLuaGlobalInt(GLFW_NATIVE_CONTEXT_API, "GLFW_NATIVE_CONTEXT_API");
	AddLuaGlobalInt(GLFW_EGL_CONTEXT_API, "GLFW_EGL_CONTEXT_API");
	AddLuaGlobalInt(GLFW_OSMESA_CONTEXT_API, "GLFW_OSMESA_CONTEXT_API");
	AddLuaGlobalInt(GLFW_ANGLE_PLATFORM_TYPE_NONE, "GLFW_ANGLE_PLATFORM_TYPE_NONE");
	AddLuaGlobalInt(GLFW_ANGLE_PLATFORM_TYPE_OPENGL, "GLFW_ANGLE_PLATFORM_TYPE_OPENGL");
	AddLuaGlobalInt(GLFW_ANGLE_PLATFORM_TYPE_OPENGLES, "GLFW_ANGLE_PLATFORM_TYPE_OPENGLES");
	AddLuaGlobalInt(GLFW_ANGLE_PLATFORM_TYPE_D3D9, "GLFW_ANGLE_PLATFORM_TYPE_D3D9");
	AddLuaGlobalInt(GLFW_ANGLE_PLATFORM_TYPE_D3D11, "GLFW_ANGLE_PLATFORM_TYPE_D3D11");
	AddLuaGlobalInt(GLFW_ANGLE_PLATFORM_TYPE_VULKAN, "GLFW_ANGLE_PLATFORM_TYPE_VULKAN");
	AddLuaGlobalInt(GLFW_ANGLE_PLATFORM_TYPE_METAL, "GLFW_ANGLE_PLATFORM_TYPE_METAL");
	AddLuaGlobalInt(GLFW_WAYLAND_PREFER_LIBDECOR, "GLFW_WAYLAND_PREFER_LIBDECOR");
	AddLuaGlobalInt(GLFW_WAYLAND_DISABLE_LIBDECOR, "GLFW_WAYLAND_DISABLE_LIBDECOR");
	AddLuaGlobalInt(GLFW_ANY_POSITION, "GLFW_ANY_POSITION");

	AddLuaGlobalInt(GLFW_HAT_CENTERED, "GLFW_HAT_CENTERED");
	AddLuaGlobalInt(GLFW_HAT_UP, "GLFW_HAT_UP");
	AddLuaGlobalInt(GLFW_HAT_RIGHT, "GLFW_HAT_RIGHT");
	AddLuaGlobalInt(GLFW_HAT_DOWN, "GLFW_HAT_DOWN");
	AddLuaGlobalInt(GLFW_HAT_LEFT, "GLFW_HAT_LEFT");
	AddLuaGlobalInt(GLFW_HAT_RIGHT_UP, "GLFW_HAT_RIGHT_UP");
	AddLuaGlobalInt(GLFW_HAT_RIGHT_DOWN, "GLFW_HAT_RIGHT_DOWN");
	AddLuaGlobalInt(GLFW_HAT_LEFT_UP, "GLFW_HAT_LEFT_UP");
	AddLuaGlobalInt(GLFW_HAT_LEFT_DOWN, "GLFW_HAT_LEFT_DOWN");

	AddLuaGlobalInt(GLFW_KEY_SPACE, "GLFW_KEY_SPACE");
	AddLuaGlobalInt(GLFW_KEY_APOSTROPHE, "GLFW_KEY_APOSTROPHE");
	AddLuaGlobalInt(GLFW_KEY_COMMA, "GLFW_KEY_COMMA");
	AddLuaGlobalInt(GLFW_KEY_MINUS, "GLFW_KEY_MINUS");
	AddLuaGlobalInt(GLFW_KEY_PERIOD, "GLFW_KEY_PERIOD");
	AddLuaGlobalInt(GLFW_KEY_SLASH, "GLFW_KEY_SLASH");
	AddLuaGlobalInt(GLFW_KEY_0, "GLFW_KEY_0");
	AddLuaGlobalInt(GLFW_KEY_1, "GLFW_KEY_1");
	AddLuaGlobalInt(GLFW_KEY_2, "GLFW_KEY_2");
	AddLuaGlobalInt(GLFW_KEY_3, "GLFW_KEY_3");
	AddLuaGlobalInt(GLFW_KEY_4, "GLFW_KEY_4");
	AddLuaGlobalInt(GLFW_KEY_5, "GLFW_KEY_5");
	AddLuaGlobalInt(GLFW_KEY_6, "GLFW_KEY_6");
	AddLuaGlobalInt(GLFW_KEY_7, "GLFW_KEY_7");
	AddLuaGlobalInt(GLFW_KEY_8, "GLFW_KEY_8");
	AddLuaGlobalInt(GLFW_KEY_9, "GLFW_KEY_9");
	AddLuaGlobalInt(GLFW_KEY_SEMICOLON, "GLFW_KEY_SEMICOLON");
	AddLuaGlobalInt(GLFW_KEY_EQUAL, "GLFW_KEY_EQUAL");
	AddLuaGlobalInt(GLFW_KEY_A, "GLFW_KEY_A");
	AddLuaGlobalInt(GLFW_KEY_B, "GLFW_KEY_B");
	AddLuaGlobalInt(GLFW_KEY_C, "GLFW_KEY_C");
	AddLuaGlobalInt(GLFW_KEY_D, "GLFW_KEY_D");
	AddLuaGlobalInt(GLFW_KEY_E, "GLFW_KEY_E");
	AddLuaGlobalInt(GLFW_KEY_F, "GLFW_KEY_F");
	AddLuaGlobalInt(GLFW_KEY_G, "GLFW_KEY_G");
	AddLuaGlobalInt(GLFW_KEY_H, "GLFW_KEY_H");
	AddLuaGlobalInt(GLFW_KEY_I, "GLFW_KEY_I");
	AddLuaGlobalInt(GLFW_KEY_J, "GLFW_KEY_J");
	AddLuaGlobalInt(GLFW_KEY_K, "GLFW_KEY_K");
	AddLuaGlobalInt(GLFW_KEY_L, "GLFW_KEY_L");
	AddLuaGlobalInt(GLFW_KEY_M, "GLFW_KEY_M");
	AddLuaGlobalInt(GLFW_KEY_N, "GLFW_KEY_N");
	AddLuaGlobalInt(GLFW_KEY_O, "GLFW_KEY_O");
	AddLuaGlobalInt(GLFW_KEY_P, "GLFW_KEY_P");
	AddLuaGlobalInt(GLFW_KEY_Q, "GLFW_KEY_Q");
	AddLuaGlobalInt(GLFW_KEY_R, "GLFW_KEY_R");
	AddLuaGlobalInt(GLFW_KEY_S, "GLFW_KEY_S");
	AddLuaGlobalInt(GLFW_KEY_T, "GLFW_KEY_T");
	AddLuaGlobalInt(GLFW_KEY_U, "GLFW_KEY_U");
	AddLuaGlobalInt(GLFW_KEY_V, "GLFW_KEY_V");
	AddLuaGlobalInt(GLFW_KEY_W, "GLFW_KEY_W");
	AddLuaGlobalInt(GLFW_KEY_X, "GLFW_KEY_X");
	AddLuaGlobalInt(GLFW_KEY_Y, "GLFW_KEY_Y");
	AddLuaGlobalInt(GLFW_KEY_Z, "GLFW_KEY_Z");
	AddLuaGlobalInt(GLFW_KEY_LEFT_BRACKET, "GLFW_KEY_LEFT_BRACKET");
	AddLuaGlobalInt(GLFW_KEY_BACKSLASH, "GLFW_KEY_BACKSLASH");
	AddLuaGlobalInt(GLFW_KEY_RIGHT_BRACKET, "GLFW_KEY_RIGHT_BRACKET");
	AddLuaGlobalInt(GLFW_KEY_GRAVE_ACCENT, "GLFW_KEY_GRAVE_ACCENT");
	AddLuaGlobalInt(GLFW_KEY_WORLD_1, "GLFW_KEY_WORLD_1");
	AddLuaGlobalInt(GLFW_KEY_WORLD_2, "GLFW_KEY_WORLD_2");
	AddLuaGlobalInt(GLFW_KEY_ESCAPE, "GLFW_KEY_ESCAPE");
	AddLuaGlobalInt(GLFW_KEY_ENTER, "GLFW_KEY_ENTER");
	AddLuaGlobalInt(GLFW_KEY_TAB, "GLFW_KEY_TAB");
	AddLuaGlobalInt(GLFW_KEY_BACKSPACE, "GLFW_KEY_BACKSPACE");
	AddLuaGlobalInt(GLFW_KEY_INSERT, "GLFW_KEY_INSERT");
	AddLuaGlobalInt(GLFW_KEY_DELETE, "GLFW_KEY_DELETE");
	AddLuaGlobalInt(GLFW_KEY_RIGHT, "GLFW_KEY_RIGHT");
	AddLuaGlobalInt(GLFW_KEY_LEFT, "GLFW_KEY_LEFT");
	AddLuaGlobalInt(GLFW_KEY_DOWN, "GLFW_KEY_DOWN");
	AddLuaGlobalInt(GLFW_KEY_UP, "GLFW_KEY_UP");
	AddLuaGlobalInt(GLFW_KEY_PAGE_UP, "GLFW_KEY_PAGE_UP");
	AddLuaGlobalInt(GLFW_KEY_PAGE_DOWN, "GLFW_KEY_PAGE_DOWN");
	AddLuaGlobalInt(GLFW_KEY_HOME, "GLFW_KEY_HOME");
	AddLuaGlobalInt(GLFW_KEY_END, "GLFW_KEY_END");
	AddLuaGlobalInt(GLFW_KEY_CAPS_LOCK, "GLFW_KEY_CAPS_LOCK");
	AddLuaGlobalInt(GLFW_KEY_SCROLL_LOCK, "GLFW_KEY_SCROLL_LOCK");
	AddLuaGlobalInt(GLFW_KEY_NUM_LOCK, "GLFW_KEY_NUM_LOCK");
	AddLuaGlobalInt(GLFW_KEY_PRINT_SCREEN, "GLFW_KEY_PRINT_SCREEN");
	AddLuaGlobalInt(GLFW_KEY_PAUSE, "GLFW_KEY_PAUSE");
	AddLuaGlobalInt(GLFW_KEY_F1, "GLFW_KEY_F1");
	AddLuaGlobalInt(GLFW_KEY_F2, "GLFW_KEY_F2");
	AddLuaGlobalInt(GLFW_KEY_F3, "GLFW_KEY_F3");
	AddLuaGlobalInt(GLFW_KEY_F4, "GLFW_KEY_F4");
	AddLuaGlobalInt(GLFW_KEY_F5, "GLFW_KEY_F5");
	AddLuaGlobalInt(GLFW_KEY_F6, "GLFW_KEY_F6");
	AddLuaGlobalInt(GLFW_KEY_F7, "GLFW_KEY_F7");
	AddLuaGlobalInt(GLFW_KEY_F8, "GLFW_KEY_F8");
	AddLuaGlobalInt(GLFW_KEY_F9, "GLFW_KEY_F9");
	AddLuaGlobalInt(GLFW_KEY_F10, "GLFW_KEY_F10");
	AddLuaGlobalInt(GLFW_KEY_F11, "GLFW_KEY_F11");
	AddLuaGlobalInt(GLFW_KEY_F12, "GLFW_KEY_F12");
	AddLuaGlobalInt(GLFW_KEY_F13, "GLFW_KEY_F13");
	AddLuaGlobalInt(GLFW_KEY_F14, "GLFW_KEY_F14");
	AddLuaGlobalInt(GLFW_KEY_F15, "GLFW_KEY_F15");
	AddLuaGlobalInt(GLFW_KEY_F16, "GLFW_KEY_F16");
	AddLuaGlobalInt(GLFW_KEY_F17, "GLFW_KEY_F17");
	AddLuaGlobalInt(GLFW_KEY_F18, "GLFW_KEY_F18");
	AddLuaGlobalInt(GLFW_KEY_F19, "GLFW_KEY_F19");
	AddLuaGlobalInt(GLFW_KEY_F20, "GLFW_KEY_F20");
	AddLuaGlobalInt(GLFW_KEY_F21, "GLFW_KEY_F21");
	AddLuaGlobalInt(GLFW_KEY_F22, "GLFW_KEY_F22");
	AddLuaGlobalInt(GLFW_KEY_F23, "GLFW_KEY_F23");
	AddLuaGlobalInt(GLFW_KEY_F24, "GLFW_KEY_F24");
	AddLuaGlobalInt(GLFW_KEY_F25, "GLFW_KEY_F25");
	AddLuaGlobalInt(GLFW_KEY_KP_0, "GLFW_KEY_KP_0");
	AddLuaGlobalInt(GLFW_KEY_KP_1, "GLFW_KEY_KP_1");
	AddLuaGlobalInt(GLFW_KEY_KP_2, "GLFW_KEY_KP_2");
	AddLuaGlobalInt(GLFW_KEY_KP_3, "GLFW_KEY_KP_3");
	AddLuaGlobalInt(GLFW_KEY_KP_4, "GLFW_KEY_KP_4");
	AddLuaGlobalInt(GLFW_KEY_KP_5, "GLFW_KEY_KP_5");
	AddLuaGlobalInt(GLFW_KEY_KP_6, "GLFW_KEY_KP_6");
	AddLuaGlobalInt(GLFW_KEY_KP_7, "GLFW_KEY_KP_7");
	AddLuaGlobalInt(GLFW_KEY_KP_8, "GLFW_KEY_KP_8");
	AddLuaGlobalInt(GLFW_KEY_KP_9, "GLFW_KEY_KP_9");
	AddLuaGlobalInt(GLFW_KEY_KP_DECIMAL, "GLFW_KEY_KP_DECIMAL");
	AddLuaGlobalInt(GLFW_KEY_KP_DIVIDE, "GLFW_KEY_KP_DIVIDE");
	AddLuaGlobalInt(GLFW_KEY_KP_MULTIPLY, "GLFW_KEY_KP_MULTIPLY");
	AddLuaGlobalInt(GLFW_KEY_KP_SUBTRACT, "GLFW_KEY_KP_SUBTRACT");
	AddLuaGlobalInt(GLFW_KEY_KP_ADD, "GLFW_KEY_KP_ADD");
	AddLuaGlobalInt(GLFW_KEY_KP_ENTER, "GLFW_KEY_KP_ENTER");
	AddLuaGlobalInt(GLFW_KEY_KP_EQUAL, "GLFW_KEY_KP_EQUAL");
	AddLuaGlobalInt(GLFW_KEY_LEFT_SHIFT, "GLFW_KEY_LEFT_SHIFT");
	AddLuaGlobalInt(GLFW_KEY_LEFT_CONTROL, "GLFW_KEY_LEFT_CONTROL");
	AddLuaGlobalInt(GLFW_KEY_LEFT_ALT, "GLFW_KEY_LEFT_ALT");
	AddLuaGlobalInt(GLFW_KEY_LEFT_SUPER, "GLFW_KEY_LEFT_SUPER");
	AddLuaGlobalInt(GLFW_KEY_RIGHT_SHIFT, "GLFW_KEY_RIGHT_SHIFT");
	AddLuaGlobalInt(GLFW_KEY_RIGHT_CONTROL, "GLFW_KEY_RIGHT_CONTROL");
	AddLuaGlobalInt(GLFW_KEY_RIGHT_ALT, "GLFW_KEY_RIGHT_ALT");
	AddLuaGlobalInt(GLFW_KEY_RIGHT_SUPER, "GLFW_KEY_RIGHT_SUPER");
	AddLuaGlobalInt(GLFW_KEY_MENU, "GLFW_KEY_MENU");

	AddLuaGlobalInt(GLFW_MOD_SHIFT, "GLFW_MOD_SHIFT");
	AddLuaGlobalInt(GLFW_MOD_CONTROL, "GLFW_MOD_CONTROL");
	AddLuaGlobalInt(GLFW_MOD_ALT, "GLFW_MOD_ALT");
	AddLuaGlobalInt(GLFW_MOD_SUPER, "GLFW_MOD_SUPER");
	AddLuaGlobalInt(GLFW_MOD_CAPS_LOCK, "GLFW_MOD_CAPS_LOCK");
	AddLuaGlobalInt(GLFW_MOD_NUM_LOCK, "GLFW_MOD_NUM_LOCK");

	AddLuaGlobalInt(GLFW_MOUSE_BUTTON_1, "GLFW_MOUSE_BUTTON_1");
	AddLuaGlobalInt(GLFW_MOUSE_BUTTON_2, "GLFW_MOUSE_BUTTON_2");
	AddLuaGlobalInt(GLFW_MOUSE_BUTTON_3, "GLFW_MOUSE_BUTTON_3");
	AddLuaGlobalInt(GLFW_MOUSE_BUTTON_4, "GLFW_MOUSE_BUTTON_4");
	AddLuaGlobalInt(GLFW_MOUSE_BUTTON_5, "GLFW_MOUSE_BUTTON_5");
	AddLuaGlobalInt(GLFW_MOUSE_BUTTON_6, "GLFW_MOUSE_BUTTON_6");
	AddLuaGlobalInt(GLFW_MOUSE_BUTTON_7, "GLFW_MOUSE_BUTTON_7");
	AddLuaGlobalInt(GLFW_MOUSE_BUTTON_8, "GLFW_MOUSE_BUTTON_8");
	AddLuaGlobalInt(GLFW_MOUSE_BUTTON_LAST, "GLFW_MOUSE_BUTTON_LAST");
	AddLuaGlobalInt(GLFW_MOUSE_BUTTON_LEFT, "GLFW_MOUSE_BUTTON_LEFT");
	AddLuaGlobalInt(GLFW_MOUSE_BUTTON_RIGHT, "GLFW_MOUSE_BUTTON_RIGHT");
	AddLuaGlobalInt(GLFW_MOUSE_BUTTON_MIDDLE, "GLFW_MOUSE_BUTTON_MIDDLE");

	AddLuaGlobalInt(GLFW_JOYSTICK_1, "GLFW_JOYSTICK_1");
	AddLuaGlobalInt(GLFW_JOYSTICK_2, "GLFW_JOYSTICK_2");
	AddLuaGlobalInt(GLFW_JOYSTICK_3, "GLFW_JOYSTICK_3");
	AddLuaGlobalInt(GLFW_JOYSTICK_4, "GLFW_JOYSTICK_4");
	AddLuaGlobalInt(GLFW_JOYSTICK_5, "GLFW_JOYSTICK_5");
	AddLuaGlobalInt(GLFW_JOYSTICK_6, "GLFW_JOYSTICK_6");
	AddLuaGlobalInt(GLFW_JOYSTICK_7, "GLFW_JOYSTICK_7");
	AddLuaGlobalInt(GLFW_JOYSTICK_8, "GLFW_JOYSTICK_8");
	AddLuaGlobalInt(GLFW_JOYSTICK_9, "GLFW_JOYSTICK_9");
	AddLuaGlobalInt(GLFW_JOYSTICK_10, "GLFW_JOYSTICK_10");
	AddLuaGlobalInt(GLFW_JOYSTICK_11, "GLFW_JOYSTICK_11");
	AddLuaGlobalInt(GLFW_JOYSTICK_12, "GLFW_JOYSTICK_12");
	AddLuaGlobalInt(GLFW_JOYSTICK_13, "GLFW_JOYSTICK_13");
	AddLuaGlobalInt(GLFW_JOYSTICK_14, "GLFW_JOYSTICK_14");
	AddLuaGlobalInt(GLFW_JOYSTICK_15, "GLFW_JOYSTICK_15");
	AddLuaGlobalInt(GLFW_JOYSTICK_16, "GLFW_JOYSTICK_16");

	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_A, "GLFW_GAMEPAD_BUTTON_A");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_B, "GLFW_GAMEPAD_BUTTON_B");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_X, "GLFW_GAMEPAD_BUTTON_X");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_Y, "GLFW_GAMEPAD_BUTTON_Y");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_LEFT_BUMPER, "GLFW_GAMEPAD_BUTTON_LEFT_BUMPER");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER, "GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_BACK, "GLFW_GAMEPAD_BUTTON_BACK");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_START, "GLFW_GAMEPAD_BUTTON_START");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_GUIDE, "GLFW_GAMEPAD_BUTTON_GUIDE");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_LEFT_THUMB, "GLFW_GAMEPAD_BUTTON_LEFT_THUMB");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_RIGHT_THUMB, "GLFW_GAMEPAD_BUTTON_RIGHT_THUMB");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_DPAD_UP, "GLFW_GAMEPAD_BUTTON_DPAD_UP");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_DPAD_RIGHT, "GLFW_GAMEPAD_BUTTON_DPAD_RIGHT");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_DPAD_DOWN, "GLFW_GAMEPAD_BUTTON_DPAD_DOWN");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_DPAD_LEFT, "GLFW_GAMEPAD_BUTTON_DPAD_LEFT");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_LAST, "GLFW_GAMEPAD_BUTTON_LAST");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_CROSS, "GLFW_GAMEPAD_BUTTON_CROSS");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_CIRCLE, "GLFW_GAMEPAD_BUTTON_CIRCLE");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_SQUARE, "GLFW_GAMEPAD_BUTTON_SQUARE");
	AddLuaGlobalInt(GLFW_GAMEPAD_BUTTON_TRIANGLE, "GLFW_GAMEPAD_BUTTON_TRIANGLE");



	lua_createtable(L, 0, 5);

	lua_pushlightuserdata(L, glWindow);
	lua_setfield(L, -2, "data");

	lua_pushlightuserdata(L, glWindow);
	lua_pushcclosure(L, LuaFN_GLFWGetCursorPos, 1);
	lua_setfield(L, -2, "GetCursorPos");

	lua_pushlightuserdata(L, glWindow);
	lua_pushcclosure(L, LuaFN_GLFWSetInputMode, 1);
	lua_setfield(L, -2, "SetInputMode");

	lua_setglobal(L, "glfw");
}