shaders\glslc.exe shaders/auto-exposure.frag -o shaders/auto-exposure_pixl.spv
shaders\glslc.exe shaders/bloom.frag -o shaders/bloom_pixl.spv
shaders\glslc.exe shaders/bloomblurX.frag -o shaders/bloomblurX_pixl.spv
shaders\glslc.exe shaders/bloomblurY.frag -o shaders/bloomblurY_pixl.spv
shaders\glslc.exe shaders/bloomCombine.frag -o shaders/bloomCombine_pixl.spv
shaders\glslc.exe shaders/building.frag -o shaders/building_pixl.spv
shaders\glslc.exe shaders/clearcoat.frag -o shaders/clearcoat_pixl.spv
shaders\glslc.exe shaders/core-debug2d.frag -o shaders/core-debug2d_pixl.spv
shaders\glslc.exe shaders/core-debug2d.vert -o shaders/core-debug2d_vert.spv
shaders\glslc.exe shaders/core-debug3d.frag -o shaders/core-debug3d_pixl.spv
shaders\glslc.exe shaders/core-debug3d.vert -o shaders/core-debug3d_vert.spv
shaders\glslc.exe shaders/core-light-masked-static.frag -o shaders/core-light-masked-static_pixl.spv
shaders\glslc.exe shaders/core-light-masked-static.vert -o shaders/core-light-masked-static_vert.spv
shaders\glslc.exe shaders/core-light-static.frag -o shaders/core-light-static_pixl.spv
shaders\glslc.exe shaders/core-light-static.vert -o shaders/core-light-static_vert.spv
shaders\glslc.exe shaders/core-outline.frag -o shaders/core-outline_pixl.spv
shaders\glslc.exe shaders/core-outline.vert -o shaders/core-outline_vert.spv
shaders\glslc.exe shaders/depthoffield.frag -o shaders/depthoffield_pixl.spv
shaders\glslc.exe shaders/depthoffield2.frag -o shaders/depthoffield2_pixl.spv
shaders\glslc.exe shaders/diffuse-masked.frag -o shaders/diffuse-masked_pixl.spv
shaders\glslc.exe shaders/diffuse.frag -o shaders/diffuse_pixl.spv
shaders\glslc.exe shaders/fog.frag -o shaders/fog_pixl.spv
shaders\glslc.exe shaders/foliage2sided.frag -o shaders/foliage2sided_pixl.spv
shaders\glslc.exe shaders/fxaa.frag -o shaders/fxaa_pixl.spv
shaders\glslc.exe shaders/glass.frag -o shaders/glass_pixl.spv
shaders\glslc.exe shaders/metal-masked.frag -o shaders/metal-masked_pixl.spv
shaders\glslc.exe shaders/metal.frag -o shaders/metal_pixl.spv
shaders\glslc.exe shaders/motionblur.frag -o shaders/motionblur_pixl.spv
shaders\glslc.exe shaders/othereffects.frag -o shaders/othereffects_pixl.spv
shaders\glslc.exe shaders/post-fog.frag -o shaders/post-fog_pixl.spv
shaders\glslc.exe shaders/post.frag -o shaders/post_pixl.spv
shaders\glslc.exe shaders/post.vert -o shaders/post_vert.spv
shaders\glslc.exe shaders/shadowMapViewer.frag -o shaders/shadowMapViewer_pixl.spv
shaders\glslc.exe shaders/shadowMapViewer.vert -o shaders/shadowMapViewer_vert.spv
shaders\glslc.exe shaders/shadowPass-spot.frag -o shaders/shadowPass-spot_pixl.spv
shaders\glslc.exe shaders/shadowPass-sun.frag -o shaders/shadowPass-sun_pixl.spv
shaders\glslc.exe shaders/skybox.frag -o shaders/skybox_pixl.spv
shaders\glslc.exe shaders/skybox.vert -o shaders/skybox_vert.spv
shaders\glslc.exe shaders/ssao-blur.frag -o shaders/ssao-blur_pixl.spv
shaders\glslc.exe shaders/ssao.frag -o shaders/ssao_pixl.spv
shaders\glslc.exe shaders/ssr.frag -o shaders/ssr_pixl.spv
shaders\glslc.exe shaders/ssrcombine.frag -o shaders/ssrcombine_pixl.spv
shaders\glslc.exe shaders/staticVert.frag -o shaders/staticVert_pixl.spv
shaders\glslc.exe shaders/staticVert.vert -o shaders/staticVert_vert.spv
shaders\glslc.exe shaders/testcompute.comp -o shaders/testcompute_comp.spv
shaders\glslc.exe shaders/water-forward.frag -o shaders/water-forward_pixl.spv
shaders\glslc.exe shaders/water-forward.vert -o shaders/water-forward_vert.spv
shaders\glslc.exe shaders/water.frag -o shaders/water_pixl.spv
shaders\glslc.exe shaders/water.vert -o shaders/water_vert.spv
pause
